# Generated by Django 3.0.8 on 2020-08-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netvelotest', '0002_auto_20200724_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadtime', models.DecimalField(decimal_places=3, max_digits=65, null=True)),
                ('captured_date', models.DateTimeField(null=True)),
                ('speedtest_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netvelotest.Netvelocity')),
            ],
        ),
    ]
