# Generated by Django 3.0.8 on 2020-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netvelotest', '0004_netvelocity_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speedhistory',
            old_name='loadtime',
            new_name='download',
        ),
        migrations.AddField(
            model_name='speedhistory',
            name='isp',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='speedhistory',
            name='ping',
            field=models.DecimalField(decimal_places=3, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='speedhistory',
            name='upload',
            field=models.DecimalField(decimal_places=3, max_digits=65, null=True),
        ),
    ]
