# Generated by Django 3.0.8 on 2020-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtimer', '0002_auto_20200724_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtimer',
            name='time',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=65, null=True),
        ),
    ]
